name = input ("enter your name")
age = int(input ("entre your age"))
marks = float (input ("entre your marks"))
print ("welcome",name)
print("age", age)
print ("marks", marks)
first = float(input("entre a number:"))
second = float (input ("entre a number:"))
print ("sum=",first+second)