collection = {1,2,3}
print (type (collection))
print (collection)
print (len(collection))
collection2 = set((1,2,3,7,8,9,0,"aryan"))
collection2.add ((1,2,3,4))
print (collection2)
print (type(collection2))
collection2.clear()
print (collection2)
print (len(collection2))
print (collection.pop())
print (collection.union(collection2))
print (collection2.intersection(collection))